CREATE EXTENSION IF NOT EXISTS pg_orca;
CREATE TABLE quant_outer(i int, v int);
CREATE TABLE quant_inner(v int);
CREATE TABLE quant_equal(v int);
CREATE TABLE quant_empty(v int);
CREATE TABLE quant_keys(v int, k numeric);
CREATE TABLE quant_extrema(s smallint, b bigint);
INSERT INTO quant_outer VALUES (1, NULL), (2, 1), (3, 2), (4, 3);
INSERT INTO quant_inner VALUES (1), (NULL), (2), (2);
INSERT INTO quant_equal VALUES (1), (1);
INSERT INTO quant_keys VALUES (1, 1), (1, 2), (2, 1), (NULL, 1);
INSERT INTO quant_extrema VALUES (1, 1), (NULL, NULL), (2, 2);
ANALYZE quant_outer;
ANALYZE quant_inner;
ANALYZE quant_equal;
ANALYZE quant_empty;
ANALYZE quant_keys;
ANALYZE quant_extrema;
