CREATE EXTENSION IF NOT EXISTS pg_orca;
CREATE TABLE apply_outer(i int);
CREATE TABLE apply_inner(j int);
CREATE TABLE apply_empty(j int);
CREATE TABLE apply_pairs(i int, k int);
INSERT INTO apply_outer VALUES (NULL),(1),(2),(2);
INSERT INTO apply_inner VALUES (NULL),(0),(1),(1);
INSERT INTO apply_pairs VALUES (NULL,1),(1,2),(2,1),(2,1),(0,2),(1,NULL);
ANALYZE apply_outer;
ANALYZE apply_inner;
ANALYZE apply_empty;
ANALYZE apply_pairs;
